/**
 * Fixture connector export JSON, matching the REAL shapes printed by
 * `erp-mcp export` / `crm-mcp export` / `email-mcp export`
 * (hap-erp-mcp/hap-crm-mcp/hap-email-mcp `src/cli.ts`, `src/db.ts` — read
 * 2026-10-05, see report/types.ts doc comment). Not generated by mocking the
 * connector — these are plain data objects standing in for its stdout, which
 * is exactly the module boundary `connector-export.ts` is tested across.
 */
import type { EmailExport, ErpExport, CrmExport } from '../../../src/lib/report/types';

export function buildEmailExport(overrides: Partial<EmailExport> = {}): EmailExport {
  return {
    mode: 'simulation',
    exported_at: '2026-10-05T12:00:00.000Z',
    inbox: [],
    sent: [],
    changes: [],
    refusals: [],
    ...overrides,
  };
}

export function buildErpExport(overrides: Partial<ErpExport> = {}): ErpExport {
  return {
    mode: 'simulation',
    exported_at: '2026-10-05T12:00:00.000Z',
    quotes: [],
    orders: [],
    changes: [],
    refusals: [],
    ...overrides,
  };
}

export function buildCrmExport(overrides: Partial<CrmExport> = {}): CrmExport {
  return {
    mode: 'simulation',
    exported_at: '2026-10-05T12:00:00.000Z',
    contacts: [],
    deals: [],
    tasks: [],
    activities: [],
    changes: [],
    refusals: [],
    ...overrides,
  };
}
