# Does a toast survive the posting process exiting immediately?
# A: spawn detached, exit at once (what the gateway does today).
# B: same, but stay alive 3 seconds after Show().
# ASCII only + BOM: PowerShell 5.1 reads .ps1 as ANSI otherwise.

Write-Host "Posting A (immediate exit). Watch for a toast..."
Start-Process powershell -WindowStyle Hidden -ArgumentList '-NoProfile','-NonInteractive','-Command','$ErrorActionPreference=''SilentlyContinue''; $aumid=''Suveren.Gateway''; $reg="HKCU:\Software\Classes\AppUserModelId\$aumid"; if (-not (Test-Path $reg)) { New-Item -Path $reg -Force | Out-Null }; New-ItemProperty -Path $reg -Name DisplayName -Value ''Suveren'' -PropertyType String -Force | Out-Null; New-ItemProperty -Path $reg -Name IconUri -Value ''C:\Users\Public\suveren-icon.png'' -PropertyType String -Force | Out-Null; [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null; [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom, ContentType=WindowsRuntime] | Out-Null; $doc = New-Object Windows.Data.Xml.Dom.XmlDocument; $doc.LoadXml(''<toast activationType="protocol" launch="https://www.suveren.ai"><visual><binding template="ToastGeneric"><text>Suveren</text><text>Test A - posted then exited immediately</text><image placement="appLogoOverride" src="C:\Users\Public\suveren-icon.png"/></binding></visual><audio src="ms-winsoundevent:Notification.Default"/></toast>''); $toast = New-Object Windows.UI.Notifications.ToastNotification $doc; [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($aumid).Show($toast)'
Start-Sleep -Seconds 8
Write-Host "Posting B (stays alive 3s). Watch for a toast..."
Start-Process powershell -WindowStyle Hidden -ArgumentList '-NoProfile','-NonInteractive','-Command','$ErrorActionPreference=''SilentlyContinue''; $aumid=''Suveren.Gateway''; $reg="HKCU:\Software\Classes\AppUserModelId\$aumid"; if (-not (Test-Path $reg)) { New-Item -Path $reg -Force | Out-Null }; New-ItemProperty -Path $reg -Name DisplayName -Value ''Suveren'' -PropertyType String -Force | Out-Null; New-ItemProperty -Path $reg -Name IconUri -Value ''C:\Users\Public\suveren-icon.png'' -PropertyType String -Force | Out-Null; [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType=WindowsRuntime] | Out-Null; [Windows.Data.Xml.Dom.XmlDocument, Windows.Data.Xml.Dom, ContentType=WindowsRuntime] | Out-Null; $doc = New-Object Windows.Data.Xml.Dom.XmlDocument; $doc.LoadXml(''<toast activationType="protocol" launch="https://www.suveren.ai"><visual><binding template="ToastGeneric"><text>Suveren</text><text>Test B - posted then waited 3s</text><image placement="appLogoOverride" src="C:\Users\Public\suveren-icon.png"/></binding></visual><audio src="ms-winsoundevent:Notification.Default"/></toast>''); $toast = New-Object Windows.UI.Notifications.ToastNotification $doc; [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($aumid).Show($toast); Start-Sleep -Seconds 3'
Start-Sleep -Seconds 8
Write-Host ""
Write-Host "Which toasts appeared? A only / B only / both / neither"
